### ISSUE TITLE
Svært høyt minnebruk - normalt?

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/dataservice-publisher-sparql-service#45]
Memreq til podden er på ca 1,6GiB, men den bruker i snitt rundt 7-12GiB.
Ser ut som den jobber seg oppover før den blir evicted med jevne mellomrom.
Minnelekkasje?
Noe annet?

**Comment by valosnah** [comment]
Problemet er fortsatt der etter oppdatering av garbage-collection.
Det kan virke som dataservice-publisher holder en permanent åpen connection til sparql, og dette fører til akkumulering av minnebruk

**Comment by valosnah** [comment]
Testet ved å skru av dataservice-publisher. Minnebruket flater ut med en gang.

**Comment by NilsOveTen** [comment]
Beste løsning er nok å bare stenge ned og arkivere denne løsningen. Se https://github.com/Informasjonsforvaltning/dataservice-publisher/issues/132

**Comment by valosnah** [comment]
Arkiveres, lukker issue
